import { StatType, AppIcon } from "@royal-code/shared/domain";
import { SegmentedBarConfig } from "@royal-code/ui/meters";

/**
 * @interface CharacterStatDisplayItem
 * @description Structure for displaying a single core character statistic,
 *              including its UI configuration for a UiStatBarComponent.
 *              This is typically generated by a selector by combining CharacterStats
 *              with StatDefinitions.
 */
export interface CharacterStatDisplayItem {
  /** The type or ID of the statistic. */
  type: StatType | string;
  /** Translatable key for the statistic's name (for UiMeterDisplayComponent's labelKey). */
  labelKey: string;
  /** Current value of the statistic. */
  currentValue: number;
  /** Maximum possible value of the statistic. */
  maxValue: number;
  /** The icon to be displayed for this stat (for UiMeterDisplayComponent's icon). */
  icon: AppIcon;
  /** CSS class for the icon's color (for UiMeterDisplayComponent's iconColorClass). */
  iconColorClass: string;
  /** Formatted text representing the value, e.g., "15 / 20" (for UiMeterDisplayComponent's valueText). */
  valueText: string;
  /** Optional translatable key for a short description of the stat's effect. */
  effectDescriptionKey?: string;
  /** Configuration object specifically for the `UiSegmentedBarComponent` (passed via visualizationContext). */
  barConfig: SegmentedBarConfig;
}
