/**
 * @file icon.model.ts (Shared Domain)
 * @Version 6.0.0 (Definitive, Fully Consolidated & Categorized Lucide Icons)
 * @Author Royal-Code MonorepoAppDevAI & User
 * @Date 2025-08-30
 * @Description
 *   Het definitieve, complete en volledig geconsolideerde datamodel voor alle Lucide iconen
 *   die in de applicatie worden gebruikt. Deze enum combineert *alle* eerder gedefinieerde iconen
 *   uit alle bronnen in logische categorieën, met zorgvuldige deduplicatie en validatie op ontbrekende entries.
 */
export enum AppIcon {
  // --- Algemeen & Navigatie ---
  Activity = 'activity',
  AlertCircle = 'alert-circle',
  AlertTriangle = 'alert-triangle',
  ArrowDown = 'arrow-down',
  ArrowDownCircle = 'arrow-down-circle',
  ArrowLeft = 'arrow-left',
  ArrowRight = 'arrow-right',
  ArrowUp = 'arrow-up',
  Check = 'check',
  CheckCircle = 'check-circle',
  ChevronDown = 'chevron-down',
  ChevronLeft = 'chevron-left',
  ChevronRight = 'chevron-right',
  ChevronUp = 'chevron-up',
  CircleCheck = 'circle-check',
  CircleDot = 'circle-dot',
  CircleHelp = 'circle-help',
  CircleX = 'circle-x',
  CornerDownRight = 'corner-down-right',
  Download = 'download',
  Eye = 'eye',
  EyeOff = 'eye-off',
  Gauge = 'gauge',
  Grid = 'grid',
  Hand = 'hand',
  HelpCircle = 'help-circle',
  Home = 'home',
  Info = 'info',
  List = 'list',
  Loader = 'loader',
  Menu = 'menu',
  Minus = 'minus',
  MoreHorizontal = 'more-horizontal',
  MoreVertical = 'more-vertical',
  PanelLeftClose = 'panel-left-close',
  PanelLeftOpen = 'panel-left-open',
  PanelRightClose = 'panel-right-close',
  PanelRightOpen = 'panel-right-open',
  Plus = 'plus',
  Plug = 'plug',
  RefreshCcw = 'refresh-ccw',
  RefreshCw = 'refresh-cw',
  RotateCw = 'rotate-cw',
  SearchMagnifier = 'search-magnifier',
  Route = 'route',
  Search = 'search',
  SearchX = 'search-x',
  Send = 'send',
  Settings = 'settings',
  ClipboardCheck = 'clipboard-check',
  Share = 'share',
  Tool = 'tool',
  Upload = 'upload',
  X = 'x',
  XCircle = 'x-circle',
  Filter = 'filter',
  Tree = 'tree',

  // --- Gebruikers & Authenticatie ---
  Key = 'key',
  Lock = 'lock',
  LogIn = 'log-in',
  LogOut = 'log-out',
  User = 'user',
  UserCheck = 'user-check',
  UserCircle = 'user-circle',
  UserMinus = 'user-minus',
  UserPlus = 'user-plus',
  Users = 'users',
  UserX = 'user-x',

  // --- Status & Notificaties ---
  BadgeCheck = 'badge-check',
  Bell = 'bell',
  CheckCheck = 'check-check',
  Flash = 'flash',
  LifeBuoy = 'life-buoy',
  Shield = 'shield',
  ShieldCheck = 'shield-check',
  GitBranch = 'git-branch',
  ShieldX = 'shield-x',

  // --- Media & Bestanden ---
  Camera = 'camera',
  Film = 'film',
  File = 'file',
  FileArchive = 'file-archive',
  FileAudio = 'file-audio',
  FileBinary = 'file-binary',
  FileBinary2 = 'file-binary-2',
  FileCode = 'file-code',
  FileCsv = 'file-csv',
  FileCsv2 = 'file-csv-2',
  FileImage = 'file-image',
  FileJson = 'file-json',
  FileJson2 = 'file-json-2',
  FilePdf = 'file-pdf',
  FilePpt = 'file-ppt',
  FileQuestion = 'file-question',
  FileSpreadsheet = 'file-spreadsheet',
  FileText = 'file-text',
  FileUnknown = 'file-unknown',
  FileVideo = 'file-video',
  FileWord = 'file-word',
  FileZip = 'file-zip',
  Folder = 'folder', // Toegevoegd uit foutmelding
  FolderOpen = 'folder-open', // Toegevoegd uit foutmelding
  GripHorizontal = 'grip-horizontal',
  GripVertical = 'grip-vertical',
  Image = 'image',
  ImageOff = 'image-off',
  Monitor = 'monitor',
  Pause = 'pause',
  Play = 'play',
  PlayCircle = 'play-circle',
  Video = 'video',
  Volume = 'volume',
  Volume1 = 'volume-1',
  Volume2 = 'volume-2',
  VolumeX = 'volume-x',

  // --- Commerce & Financiën ---
  Banknote = 'banknote',
  Barcode = 'barcode',
  Coins = 'coins',
  CreditCard = 'credit-card',
  DollarSign = 'dollar-sign',
  Euro = 'euro',
  Gift = 'gift',
  Package = 'package',
  PackageOpen = 'package-open',
  Percent = 'percent',
  Pound = 'pound-sterling',
  ShoppingCart = 'shopping-cart',
  ShoppingBag = 'shopping-bag',
  ShoppingBasket = 'shopping-basket',
  ShoppingCartCheck = 'shopping-cart-check',
  Store = 'store',
  Wallet = 'wallet',
  Yen = 'yen',
  Tag = 'tag',

  // --- Locatie & Plaatsen ---
  Building = 'building',
  Building2 = 'building-2',
  Castle = 'castle',
  Landmark = 'landmark',
  LocateFixed = 'locate-fixed',
  Map = 'map',
  MapPin = 'map-pin',
  Navigation = 'navigation',

  // --- Tijd & Datum ---
  Alarm = 'alarm',
  Calendar = 'calendar',
  CalendarClock = 'calendar-clock',
  Clock = 'clock',
  Hourglass = 'hourglass',
  Timer = 'timer',

  // --- Bewerken & Beheren ---
  Edit = 'edit',
  Edit3 = 'edit-3',
  ListChecks = 'list-checks', // Toegevoegd uit foutmelding
  PenTool = 'pen-tool',
  Ruler = 'ruler',
  Slash = 'slash',
  Trash2 = 'trash-2',

  // --- Feedback & Interactie ---
  Angry = 'angry',
  Bookmark = 'bookmark',
  BookmarkCheck = 'bookmark-check',
  Frown = 'frown',
  Heart = 'heart',
  Link = 'link',
  MessageCircle = 'message-circle',
  MessageSquare = 'message-square',
  PartyPopper = 'party-popper',
  Smile = 'smile',
  SmilePlus = 'smile-plus',
  Star = 'star',
  StarHalf = 'star-half',
  StarOutline = 'star-outline',
  ThumbsDown = 'thumbs-down',
  ThumbsUp = 'thumbs-up',
  Suitcase = 'suitcase',
  Compass = 'compass',

  // --- Gaming & Entertainment ---
  Gamepad2 = 'gamepad-2',
  Trophy = 'trophy',

  // --- Algemene Objecten & Concepten ---
  Airplay = 'airplay',
  Accessory = 'link-2',
  Archery = 'archery',
  Baby = 'baby',
  BarChart = 'bar-chart',
  BatteryCharging = 'battery-charging',
  Book = 'book',
  BookOpen = 'book-open',
  Bot = 'bot',
  BowArrow = 'bow-arrow',
  Box = 'box',
  Box3d = 'box-3d', // Toegevoegd uit foutmelding (Let op: geen standaard Lucide icon)
  BrainCircuit = 'brain-circuit',
  Brick = 'brick',
  Briefcase = 'briefcase',
  Bug = 'bug',
  Car = 'car',
  Clover = 'clover',
  Cloud = 'cloud',
  CloudDownload = 'cloud-download',
  CloudLightning = 'cloud-lightning',
  CloudOff = 'cloud-off',
  CloudRain = 'cloud-rain',
  CloudSync = 'cloud-sync',
  CloudUpload = 'cloud-upload',
  Code = 'code',
  Coffee = 'coffee',
  Cone = 'cone',
  Cpu = 'cpu',
  CreditCardOff = 'credit-card-off',
  HardHat = 'hard-hat',
  Weight = 'weight',
  Aperture = 'aperture',
  Thermometer = 'thermometer',
  Ear = 'ear',
  SignalHigh = 'signal-high',
  Signal = 'signal',
  Maximize = 'maximize',
  Quote = 'quote',
  Database = 'database',
  DoorOpen = 'door-open',
  Droplets = 'droplets',
  ExternalLink = 'external-link',
  Flag = 'flag',
  Flame = 'flame',
  FlaskConical = 'flask-conical',
  Footprints = 'footprints',
  Gem = 'gem', // Toegevoegd uit foutmelding
  Ghost = 'ghost',
  GitCommit = 'git-commit',
  GitPullRequest = 'git-pull-request',
  Globe = 'globe',
  Goal = 'goal',
  GraduationCap = 'graduation-cap',
  Hammer = 'hammer',
  Handshake = 'handshake',
  Hexagon = 'hexagon',
  HeartHandshake = 'heart-handshake',
  Layers = 'layers',
  LayoutDashboard = 'layout-dashboard',
  LayoutList = 'layout-list',
  LayoutGrid = 'layout-grid',
  Leaf = 'leaf',
  Lightbulb = 'lightbulb',
  Mail = 'mail',
  Microscope = 'microscope',
  MousePointer = 'mouse-pointer',
  Moon = 'moon',
  Necklace = 'necklace',
  PaintBrush = 'paintbrush',
  Palette = 'palette',
  Phone = 'phone',
  PhoneCall = 'phone-call',
  Pickaxe = 'pickaxe',
  Power = 'power',
  Radio = 'radio',
  Printer = 'printer',
  Recycle = 'recycle',
  Rocket = 'rocket',
  Rss = 'rss',
  ScrollText = 'scroll-text',
  Server = 'server',
  Shirt = 'shirt',
  Shuffle = 'shuffle',
  Sidebar = 'sidebar',
  Sliders = 'sliders',
  Smartphone = 'smartphone',
  Space = 'space',
  Speaker = 'speaker',
  Sprout = 'sprout',
  Sparkle = 'sparkle',
  Sparkles = 'sparkles',
  Square = 'square',
  Sun = 'sun',
  SunDim = 'sun-dim',
  Sword = 'sword',
  Swords = 'swords',
  Target = 'target',
  Terminal = 'terminal',
  ToggleLeft = 'toggle-left',
  ToggleRight = 'toggle-right',
  TowerControl = 'tower-control',
  TrendingDown = 'trending-down',
  TrendingUp = 'trending-up',
  Truck = 'truck',
  Tv = 'tv',
  Watch = 'watch',
  Waves = 'waves',
  Wifi = 'wifi',
  WifiOff = 'wifi-off',
  Wind = 'wind',
  Wrench = 'wrench',
  Zap = 'zap',
  Feather = 'feather',
  ZoomIn = 'zoom-in',
  ZoomOut = 'zoom-out',
  RotateCcw = 'rotate-ccw',
  Award = 'award',

  // --- Social Media ---
  Discord = 'discord',
  Dribbble = 'dribbble',
  Facebook = 'facebook',
  Github = 'github',
  Instagram = 'instagram',
  Linkedin = 'linkedin',
  Medium = 'medium',
  Pinterest = 'pinterest',
  Reddit = 'reddit',
  Slack = 'slack',
  Snapchat = 'snapchat',
  Telegram = 'telegram',
  TikTok = 'tiktok',
  Tumblr = 'tumblr',
  Twitch = 'twitch',
  Twitter = 'twitter',
  WhatsApp = 'whatsapp',
  Youtube = 'youtube',
}